// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package collections

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const GUIDIKeyValuePair string = "02b51929-c1c4-4a7e-8940-0312b5c18500"
const SignatureIKeyValuePair string = "{02b51929-c1c4-4a7e-8940-0312b5c18500}"

type IKeyValuePair struct {
	ole.IInspectable
}

type IKeyValuePairVtbl struct {
	ole.IInspectableVtbl

	GetKey   uintptr
	GetValue uintptr
}

func (v *IKeyValuePair) VTable() *IKeyValuePairVtbl {
	return (*IKeyValuePairVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *IKeyValuePair) GetKey() (unsafe.Pointer, error) {
	var out unsafe.Pointer
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetKey,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out unsafe.Pointer
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *IKeyValuePair) GetValue() (unsafe.Pointer, error) {
	var out unsafe.Pointer
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetValue,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out unsafe.Pointer
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
