// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package dom

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/storage"
	"github.com/saltosystems/winrt-go/windows/storage/streams"
)

const SignatureXmlDocument string = "rc(Windows.Data.Xml.Dom.XmlDocument;{f7f3a506-1e87-42d6-bcfb-b8c809fa5494})"

type XmlDocument struct {
	ole.IUnknown
}

func NewXmlDocument() (*XmlDocument, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Data.Xml.Dom.XmlDocument")
	if err != nil {
		return nil, err
	}
	return (*XmlDocument)(unsafe.Pointer(inspectable)), nil
}

func (impl *XmlDocument) GetDoctype() (*XmlDocumentType, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.GetDoctype()
}

func (impl *XmlDocument) GetImplementation() (*XmlDomImplementation, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.GetImplementation()
}

func (impl *XmlDocument) GetDocumentElement() (*XmlElement, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.GetDocumentElement()
}

func (impl *XmlDocument) CreateElement(tagName string) (*XmlElement, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.CreateElement(tagName)
}

func (impl *XmlDocument) CreateDocumentFragment() (*XmlDocumentFragment, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.CreateDocumentFragment()
}

func (impl *XmlDocument) CreateTextNode(data string) (*XmlText, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.CreateTextNode(data)
}

func (impl *XmlDocument) CreateComment(data string) (*XmlComment, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.CreateComment(data)
}

func (impl *XmlDocument) CreateProcessingInstruction(target string, data string) (*XmlProcessingInstruction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.CreateProcessingInstruction(target, data)
}

func (impl *XmlDocument) CreateAttribute(name string) (*XmlAttribute, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.CreateAttribute(name)
}

func (impl *XmlDocument) CreateEntityReference(name string) (*XmlEntityReference, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.CreateEntityReference(name)
}

func (impl *XmlDocument) GetElementsByTagName(tagName string) (*XmlNodeList, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.GetElementsByTagName(tagName)
}

func (impl *XmlDocument) CreateCDataSection(data string) (*XmlCDataSection, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.CreateCDataSection(data)
}

func (impl *XmlDocument) GetDocumentUri() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.GetDocumentUri()
}

func (impl *XmlDocument) CreateAttributeNS(namespaceUri unsafe.Pointer, qualifiedName string) (*XmlAttribute, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.CreateAttributeNS(namespaceUri, qualifiedName)
}

func (impl *XmlDocument) CreateElementNS(namespaceUri unsafe.Pointer, qualifiedName string) (*XmlElement, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.CreateElementNS(namespaceUri, qualifiedName)
}

func (impl *XmlDocument) GetElementById(elementId string) (*XmlElement, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.GetElementById(elementId)
}

func (impl *XmlDocument) ImportNode(node *IXmlNode, deep bool) (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocument))
	defer itf.Release()
	v := (*iXmlDocument)(unsafe.Pointer(itf))
	return v.ImportNode(node, deep)
}

func (impl *XmlDocument) GetNodeValue() (unsafe.Pointer, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetNodeValue()
}

func (impl *XmlDocument) SetNodeValue(value unsafe.Pointer) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.SetNodeValue(value)
}

func (impl *XmlDocument) GetNodeType() (NodeType, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetNodeType()
}

func (impl *XmlDocument) GetNodeName() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetNodeName()
}

func (impl *XmlDocument) GetParentNode() (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetParentNode()
}

func (impl *XmlDocument) GetChildNodes() (*XmlNodeList, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetChildNodes()
}

func (impl *XmlDocument) GetFirstChild() (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetFirstChild()
}

func (impl *XmlDocument) GetLastChild() (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetLastChild()
}

func (impl *XmlDocument) GetPreviousSibling() (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetPreviousSibling()
}

func (impl *XmlDocument) GetNextSibling() (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetNextSibling()
}

func (impl *XmlDocument) GetAttributes() (*XmlNamedNodeMap, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetAttributes()
}

func (impl *XmlDocument) HasChildNodes() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.HasChildNodes()
}

func (impl *XmlDocument) GetOwnerDocument() (*XmlDocument, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetOwnerDocument()
}

func (impl *XmlDocument) InsertBefore(newChild *IXmlNode, referenceChild *IXmlNode) (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.InsertBefore(newChild, referenceChild)
}

func (impl *XmlDocument) ReplaceChild(newChild *IXmlNode, referenceChild *IXmlNode) (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.ReplaceChild(newChild, referenceChild)
}

func (impl *XmlDocument) RemoveChild(childNode *IXmlNode) (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.RemoveChild(childNode)
}

func (impl *XmlDocument) AppendChild(newChild *IXmlNode) (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.AppendChild(newChild)
}

func (impl *XmlDocument) CloneNode(deep bool) (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.CloneNode(deep)
}

func (impl *XmlDocument) GetNamespaceUri() (unsafe.Pointer, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetNamespaceUri()
}

func (impl *XmlDocument) GetLocalName() (unsafe.Pointer, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetLocalName()
}

func (impl *XmlDocument) GetPrefix() (unsafe.Pointer, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.GetPrefix()
}

func (impl *XmlDocument) Normalize() error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.Normalize()
}

func (impl *XmlDocument) SetPrefix(value unsafe.Pointer) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNode))
	defer itf.Release()
	v := (*IXmlNode)(unsafe.Pointer(itf))
	return v.SetPrefix(value)
}

func (impl *XmlDocument) GetXml() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNodeSerializer))
	defer itf.Release()
	v := (*IXmlNodeSerializer)(unsafe.Pointer(itf))
	return v.GetXml()
}

func (impl *XmlDocument) GetInnerText() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNodeSerializer))
	defer itf.Release()
	v := (*IXmlNodeSerializer)(unsafe.Pointer(itf))
	return v.GetInnerText()
}

func (impl *XmlDocument) SetInnerText(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNodeSerializer))
	defer itf.Release()
	v := (*IXmlNodeSerializer)(unsafe.Pointer(itf))
	return v.SetInnerText(value)
}

func (impl *XmlDocument) SelectSingleNode(xpath string) (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNodeSelector))
	defer itf.Release()
	v := (*IXmlNodeSelector)(unsafe.Pointer(itf))
	return v.SelectSingleNode(xpath)
}

func (impl *XmlDocument) SelectNodes(xpath string) (*XmlNodeList, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNodeSelector))
	defer itf.Release()
	v := (*IXmlNodeSelector)(unsafe.Pointer(itf))
	return v.SelectNodes(xpath)
}

func (impl *XmlDocument) SelectSingleNodeNS(xpath string, namespaces unsafe.Pointer) (*IXmlNode, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNodeSelector))
	defer itf.Release()
	v := (*IXmlNodeSelector)(unsafe.Pointer(itf))
	return v.SelectSingleNodeNS(xpath, namespaces)
}

func (impl *XmlDocument) SelectNodesNS(xpath string, namespaces unsafe.Pointer) (*XmlNodeList, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDIXmlNodeSelector))
	defer itf.Release()
	v := (*IXmlNodeSelector)(unsafe.Pointer(itf))
	return v.SelectNodesNS(xpath, namespaces)
}

func (impl *XmlDocument) LoadXml(xml string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocumentIO))
	defer itf.Release()
	v := (*iXmlDocumentIO)(unsafe.Pointer(itf))
	return v.LoadXml(xml)
}

func (impl *XmlDocument) LoadXmlWithSettings(xml string, loadSettings *XmlLoadSettings) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocumentIO))
	defer itf.Release()
	v := (*iXmlDocumentIO)(unsafe.Pointer(itf))
	return v.LoadXmlWithSettings(xml, loadSettings)
}

func (impl *XmlDocument) SaveToFileAsync(file *storage.IStorageFile) (*foundation.IAsyncAction, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocumentIO))
	defer itf.Release()
	v := (*iXmlDocumentIO)(unsafe.Pointer(itf))
	return v.SaveToFileAsync(file)
}

func (impl *XmlDocument) LoadXmlFromBuffer(buffer *streams.IBuffer) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocumentIO2))
	defer itf.Release()
	v := (*iXmlDocumentIO2)(unsafe.Pointer(itf))
	return v.LoadXmlFromBuffer(buffer)
}

func (impl *XmlDocument) LoadXmlFromBufferWithSettings(buffer *streams.IBuffer, loadSettings *XmlLoadSettings) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiXmlDocumentIO2))
	defer itf.Release()
	v := (*iXmlDocumentIO2)(unsafe.Pointer(itf))
	return v.LoadXmlFromBufferWithSettings(buffer, loadSettings)
}

const GUIDiXmlDocument string = "f7f3a506-1e87-42d6-bcfb-b8c809fa5494"
const SignatureiXmlDocument string = "{f7f3a506-1e87-42d6-bcfb-b8c809fa5494}"

type iXmlDocument struct {
	ole.IInspectable
}

type iXmlDocumentVtbl struct {
	ole.IInspectableVtbl

	GetDoctype                  uintptr
	GetImplementation           uintptr
	GetDocumentElement          uintptr
	CreateElement               uintptr
	CreateDocumentFragment      uintptr
	CreateTextNode              uintptr
	CreateComment               uintptr
	CreateProcessingInstruction uintptr
	CreateAttribute             uintptr
	CreateEntityReference       uintptr
	GetElementsByTagName        uintptr
	CreateCDataSection          uintptr
	GetDocumentUri              uintptr
	CreateAttributeNS           uintptr
	CreateElementNS             uintptr
	GetElementById              uintptr
	ImportNode                  uintptr
}

func (v *iXmlDocument) VTable() *iXmlDocumentVtbl {
	return (*iXmlDocumentVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iXmlDocument) GetDoctype() (*XmlDocumentType, error) {
	var out *XmlDocumentType
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDoctype,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out XmlDocumentType
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) GetImplementation() (*XmlDomImplementation, error) {
	var out *XmlDomImplementation
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetImplementation,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out XmlDomImplementation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) GetDocumentElement() (*XmlElement, error) {
	var out *XmlElement
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDocumentElement,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out XmlElement
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) CreateElement(tagName string) (*XmlElement, error) {
	var out *XmlElement
	tagNameHStr, err := ole.NewHString(tagName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().CreateElement,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(tagNameHStr),          // in string
		uintptr(unsafe.Pointer(&out)), // out XmlElement
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) CreateDocumentFragment() (*XmlDocumentFragment, error) {
	var out *XmlDocumentFragment
	hr, _, _ := syscall.SyscallN(
		v.VTable().CreateDocumentFragment,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out XmlDocumentFragment
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) CreateTextNode(data string) (*XmlText, error) {
	var out *XmlText
	dataHStr, err := ole.NewHString(data)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().CreateTextNode,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(dataHStr),             // in string
		uintptr(unsafe.Pointer(&out)), // out XmlText
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) CreateComment(data string) (*XmlComment, error) {
	var out *XmlComment
	dataHStr, err := ole.NewHString(data)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().CreateComment,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(dataHStr),             // in string
		uintptr(unsafe.Pointer(&out)), // out XmlComment
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) CreateProcessingInstruction(target string, data string) (*XmlProcessingInstruction, error) {
	var out *XmlProcessingInstruction
	targetHStr, err := ole.NewHString(target)
	if err != nil {
		return nil, err
	}
	dataHStr, err := ole.NewHString(data)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().CreateProcessingInstruction,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(targetHStr),           // in string
		uintptr(dataHStr),             // in string
		uintptr(unsafe.Pointer(&out)), // out XmlProcessingInstruction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) CreateAttribute(name string) (*XmlAttribute, error) {
	var out *XmlAttribute
	nameHStr, err := ole.NewHString(name)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().CreateAttribute,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(nameHStr),             // in string
		uintptr(unsafe.Pointer(&out)), // out XmlAttribute
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) CreateEntityReference(name string) (*XmlEntityReference, error) {
	var out *XmlEntityReference
	nameHStr, err := ole.NewHString(name)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().CreateEntityReference,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(nameHStr),             // in string
		uintptr(unsafe.Pointer(&out)), // out XmlEntityReference
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) GetElementsByTagName(tagName string) (*XmlNodeList, error) {
	var out *XmlNodeList
	tagNameHStr, err := ole.NewHString(tagName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetElementsByTagName,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(tagNameHStr),          // in string
		uintptr(unsafe.Pointer(&out)), // out XmlNodeList
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) CreateCDataSection(data string) (*XmlCDataSection, error) {
	var out *XmlCDataSection
	dataHStr, err := ole.NewHString(data)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().CreateCDataSection,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(dataHStr),             // in string
		uintptr(unsafe.Pointer(&out)), // out XmlCDataSection
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) GetDocumentUri() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDocumentUri,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iXmlDocument) CreateAttributeNS(namespaceUri unsafe.Pointer, qualifiedName string) (*XmlAttribute, error) {
	var out *XmlAttribute
	qualifiedNameHStr, err := ole.NewHString(qualifiedName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().CreateAttributeNS,
		uintptr(unsafe.Pointer(v)),             // this
		uintptr(unsafe.Pointer(&namespaceUri)), // in unsafe.Pointer
		uintptr(qualifiedNameHStr),             // in string
		uintptr(unsafe.Pointer(&out)),          // out XmlAttribute
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) CreateElementNS(namespaceUri unsafe.Pointer, qualifiedName string) (*XmlElement, error) {
	var out *XmlElement
	qualifiedNameHStr, err := ole.NewHString(qualifiedName)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().CreateElementNS,
		uintptr(unsafe.Pointer(v)),             // this
		uintptr(unsafe.Pointer(&namespaceUri)), // in unsafe.Pointer
		uintptr(qualifiedNameHStr),             // in string
		uintptr(unsafe.Pointer(&out)),          // out XmlElement
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) GetElementById(elementId string) (*XmlElement, error) {
	var out *XmlElement
	elementIdHStr, err := ole.NewHString(elementId)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetElementById,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(elementIdHStr),        // in string
		uintptr(unsafe.Pointer(&out)), // out XmlElement
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iXmlDocument) ImportNode(node *IXmlNode, deep bool) (*IXmlNode, error) {
	var out *IXmlNode
	hr, _, _ := syscall.SyscallN(
		v.VTable().ImportNode,
		uintptr(unsafe.Pointer(v)),               // this
		uintptr(unsafe.Pointer(node)),            // in IXmlNode
		uintptr(*(*byte)(unsafe.Pointer(&deep))), // in bool
		uintptr(unsafe.Pointer(&out)),            // out IXmlNode
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiXmlDocumentIO string = "6cd0e74e-ee65-4489-9ebf-ca43e87ba637"
const SignatureiXmlDocumentIO string = "{6cd0e74e-ee65-4489-9ebf-ca43e87ba637}"

type iXmlDocumentIO struct {
	ole.IInspectable
}

type iXmlDocumentIOVtbl struct {
	ole.IInspectableVtbl

	LoadXml             uintptr
	LoadXmlWithSettings uintptr
	SaveToFileAsync     uintptr
}

func (v *iXmlDocumentIO) VTable() *iXmlDocumentIOVtbl {
	return (*iXmlDocumentIOVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iXmlDocumentIO) LoadXml(xml string) error {
	xmlHStr, err := ole.NewHString(xml)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().LoadXml,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(xmlHStr),           // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iXmlDocumentIO) LoadXmlWithSettings(xml string, loadSettings *XmlLoadSettings) error {
	xmlHStr, err := ole.NewHString(xml)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().LoadXmlWithSettings,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(xmlHStr),                      // in string
		uintptr(unsafe.Pointer(loadSettings)), // in XmlLoadSettings
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iXmlDocumentIO) SaveToFileAsync(file *storage.IStorageFile) (*foundation.IAsyncAction, error) {
	var out *foundation.IAsyncAction
	hr, _, _ := syscall.SyscallN(
		v.VTable().SaveToFileAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(file)), // in storage.IStorageFile
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncAction
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiXmlDocumentIO2 string = "5d034661-7bd8-4ad5-9ebf-81e6347263b1"
const SignatureiXmlDocumentIO2 string = "{5d034661-7bd8-4ad5-9ebf-81e6347263b1}"

type iXmlDocumentIO2 struct {
	ole.IInspectable
}

type iXmlDocumentIO2Vtbl struct {
	ole.IInspectableVtbl

	LoadXmlFromBuffer             uintptr
	LoadXmlFromBufferWithSettings uintptr
}

func (v *iXmlDocumentIO2) VTable() *iXmlDocumentIO2Vtbl {
	return (*iXmlDocumentIO2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iXmlDocumentIO2) LoadXmlFromBuffer(buffer *streams.IBuffer) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().LoadXmlFromBuffer,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(buffer)), // in streams.IBuffer
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iXmlDocumentIO2) LoadXmlFromBufferWithSettings(buffer *streams.IBuffer, loadSettings *XmlLoadSettings) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().LoadXmlFromBufferWithSettings,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(unsafe.Pointer(buffer)),       // in streams.IBuffer
		uintptr(unsafe.Pointer(loadSettings)), // in XmlLoadSettings
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiXmlDocumentStatics string = "5543d254-d757-4b79-9539-232b18f50bf1"
const SignatureiXmlDocumentStatics string = "{5543d254-d757-4b79-9539-232b18f50bf1}"

type iXmlDocumentStatics struct {
	ole.IInspectable
}

type iXmlDocumentStaticsVtbl struct {
	ole.IInspectableVtbl

	XmlDocumentLoadFromUriAsync              uintptr
	XmlDocumentLoadFromUriWithSettingsAsync  uintptr
	XmlDocumentLoadFromFileAsync             uintptr
	XmlDocumentLoadFromFileWithSettingsAsync uintptr
}

func (v *iXmlDocumentStatics) VTable() *iXmlDocumentStaticsVtbl {
	return (*iXmlDocumentStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func XmlDocumentLoadFromUriAsync(uri *foundation.Uri) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Data.Xml.Dom.XmlDocument", ole.NewGUID(GUIDiXmlDocumentStatics))
	if err != nil {
		return nil, err
	}
	v := (*iXmlDocumentStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().XmlDocumentLoadFromUriAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(uri)),  // in foundation.Uri
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func XmlDocumentLoadFromUriWithSettingsAsync(uri *foundation.Uri, loadSettings *XmlLoadSettings) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Data.Xml.Dom.XmlDocument", ole.NewGUID(GUIDiXmlDocumentStatics))
	if err != nil {
		return nil, err
	}
	v := (*iXmlDocumentStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().XmlDocumentLoadFromUriWithSettingsAsync,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(unsafe.Pointer(uri)),          // in foundation.Uri
		uintptr(unsafe.Pointer(loadSettings)), // in XmlLoadSettings
		uintptr(unsafe.Pointer(&out)),         // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func XmlDocumentLoadFromFileAsync(file *storage.IStorageFile) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Data.Xml.Dom.XmlDocument", ole.NewGUID(GUIDiXmlDocumentStatics))
	if err != nil {
		return nil, err
	}
	v := (*iXmlDocumentStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().XmlDocumentLoadFromFileAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(file)), // in storage.IStorageFile
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func XmlDocumentLoadFromFileWithSettingsAsync(file *storage.IStorageFile, loadSettings *XmlLoadSettings) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Data.Xml.Dom.XmlDocument", ole.NewGUID(GUIDiXmlDocumentStatics))
	if err != nil {
		return nil, err
	}
	v := (*iXmlDocumentStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().XmlDocumentLoadFromFileWithSettingsAsync,
		uintptr(unsafe.Pointer(v)),            // this
		uintptr(unsafe.Pointer(file)),         // in storage.IStorageFile
		uintptr(unsafe.Pointer(loadSettings)), // in XmlLoadSettings
		uintptr(unsafe.Pointer(&out)),         // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
