// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package notifications

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation/collections"
)

const SignatureNotificationData string = "rc(Windows.UI.Notifications.NotificationData;{9ffd2312-9d6a-4aaf-b6ac-ff17f0c1f280})"

type NotificationData struct {
	ole.IUnknown
}

func NewNotificationData() (*NotificationData, error) {
	inspectable, err := ole.RoActivateInstance("Windows.UI.Notifications.NotificationData")
	if err != nil {
		return nil, err
	}
	return (*NotificationData)(unsafe.Pointer(inspectable)), nil
}

func (impl *NotificationData) GetValues() (*collections.IMap, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiNotificationData))
	defer itf.Release()
	v := (*iNotificationData)(unsafe.Pointer(itf))
	return v.GetValues()
}

func (impl *NotificationData) GetSequenceNumber() (uint32, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiNotificationData))
	defer itf.Release()
	v := (*iNotificationData)(unsafe.Pointer(itf))
	return v.GetSequenceNumber()
}

func (impl *NotificationData) SetSequenceNumber(value uint32) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiNotificationData))
	defer itf.Release()
	v := (*iNotificationData)(unsafe.Pointer(itf))
	return v.SetSequenceNumber(value)
}

const GUIDiNotificationData string = "9ffd2312-9d6a-4aaf-b6ac-ff17f0c1f280"
const SignatureiNotificationData string = "{9ffd2312-9d6a-4aaf-b6ac-ff17f0c1f280}"

type iNotificationData struct {
	ole.IInspectable
}

type iNotificationDataVtbl struct {
	ole.IInspectableVtbl

	GetValues         uintptr
	GetSequenceNumber uintptr
	SetSequenceNumber uintptr
}

func (v *iNotificationData) VTable() *iNotificationDataVtbl {
	return (*iNotificationDataVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iNotificationData) GetValues() (*collections.IMap, error) {
	var out *collections.IMap
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetValues,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IMap
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iNotificationData) GetSequenceNumber() (uint32, error) {
	var out uint32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSequenceNumber,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iNotificationData) SetSequenceNumber(value uint32) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetSequenceNumber,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in uint32
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiNotificationDataFactory string = "23c1e33a-1c10-46fb-8040-dec384621cf8"
const SignatureiNotificationDataFactory string = "{23c1e33a-1c10-46fb-8040-dec384621cf8}"

type iNotificationDataFactory struct {
	ole.IInspectable
}

type iNotificationDataFactoryVtbl struct {
	ole.IInspectableVtbl

	NotificationDataCreateNotificationDataWithValuesAndSequenceNumber uintptr
	NotificationDataCreateNotificationDataWithValues                  uintptr
}

func (v *iNotificationDataFactory) VTable() *iNotificationDataFactoryVtbl {
	return (*iNotificationDataFactoryVtbl)(unsafe.Pointer(v.RawVTable))
}

func NotificationDataCreateNotificationDataWithValuesAndSequenceNumber(initialValues *collections.IIterable, sequenceNumber uint32) (*NotificationData, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.UI.Notifications.NotificationData", ole.NewGUID(GUIDiNotificationDataFactory))
	if err != nil {
		return nil, err
	}
	v := (*iNotificationDataFactory)(unsafe.Pointer(inspectable))

	var out *NotificationData
	hr, _, _ := syscall.SyscallN(
		v.VTable().NotificationDataCreateNotificationDataWithValuesAndSequenceNumber,
		uintptr(unsafe.Pointer(v)),             // this
		uintptr(unsafe.Pointer(initialValues)), // in collections.IIterable
		uintptr(sequenceNumber),                // in uint32
		uintptr(unsafe.Pointer(&out)),          // out NotificationData
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func NotificationDataCreateNotificationDataWithValues(initialValues *collections.IIterable) (*NotificationData, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.UI.Notifications.NotificationData", ole.NewGUID(GUIDiNotificationDataFactory))
	if err != nil {
		return nil, err
	}
	v := (*iNotificationDataFactory)(unsafe.Pointer(inspectable))

	var out *NotificationData
	hr, _, _ := syscall.SyscallN(
		v.VTable().NotificationDataCreateNotificationDataWithValues,
		uintptr(unsafe.Pointer(v)),             // this
		uintptr(unsafe.Pointer(initialValues)), // in collections.IIterable
		uintptr(unsafe.Pointer(&out)),          // out NotificationData
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
