// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package notifications

type NotificationMirroring int32

const SignatureNotificationMirroring string = "enum(Windows.UI.Notifications.NotificationMirroring;i4)"

const (
	NotificationMirroringAllowed  NotificationMirroring = 0
	NotificationMirroringDisabled NotificationMirroring = 1
)
