// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package notifications

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/data/xml/dom"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureToastNotification string = "rc(Windows.UI.Notifications.ToastNotification;{997e2675-059e-4e60-8b06-1760917c8b80})"

type ToastNotification struct {
	ole.IUnknown
}

func (impl *ToastNotification) GetContent() (*dom.XmlDocument, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification))
	defer itf.Release()
	v := (*iToastNotification)(unsafe.Pointer(itf))
	return v.GetContent()
}

func (impl *ToastNotification) SetExpirationTime(value *foundation.IReference) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification))
	defer itf.Release()
	v := (*iToastNotification)(unsafe.Pointer(itf))
	return v.SetExpirationTime(value)
}

func (impl *ToastNotification) GetExpirationTime() (*foundation.IReference, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification))
	defer itf.Release()
	v := (*iToastNotification)(unsafe.Pointer(itf))
	return v.GetExpirationTime()
}

func (impl *ToastNotification) AddDismissed(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification))
	defer itf.Release()
	v := (*iToastNotification)(unsafe.Pointer(itf))
	return v.AddDismissed(handler)
}

func (impl *ToastNotification) RemoveDismissed(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification))
	defer itf.Release()
	v := (*iToastNotification)(unsafe.Pointer(itf))
	return v.RemoveDismissed(token)
}

func (impl *ToastNotification) AddActivated(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification))
	defer itf.Release()
	v := (*iToastNotification)(unsafe.Pointer(itf))
	return v.AddActivated(handler)
}

func (impl *ToastNotification) RemoveActivated(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification))
	defer itf.Release()
	v := (*iToastNotification)(unsafe.Pointer(itf))
	return v.RemoveActivated(token)
}

func (impl *ToastNotification) AddFailed(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification))
	defer itf.Release()
	v := (*iToastNotification)(unsafe.Pointer(itf))
	return v.AddFailed(handler)
}

func (impl *ToastNotification) RemoveFailed(token foundation.EventRegistrationToken) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification))
	defer itf.Release()
	v := (*iToastNotification)(unsafe.Pointer(itf))
	return v.RemoveFailed(token)
}

func (impl *ToastNotification) SetTag(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification2))
	defer itf.Release()
	v := (*iToastNotification2)(unsafe.Pointer(itf))
	return v.SetTag(value)
}

func (impl *ToastNotification) GetTag() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification2))
	defer itf.Release()
	v := (*iToastNotification2)(unsafe.Pointer(itf))
	return v.GetTag()
}

func (impl *ToastNotification) SetGroup(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification2))
	defer itf.Release()
	v := (*iToastNotification2)(unsafe.Pointer(itf))
	return v.SetGroup(value)
}

func (impl *ToastNotification) GetGroup() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification2))
	defer itf.Release()
	v := (*iToastNotification2)(unsafe.Pointer(itf))
	return v.GetGroup()
}

func (impl *ToastNotification) SetSuppressPopup(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification2))
	defer itf.Release()
	v := (*iToastNotification2)(unsafe.Pointer(itf))
	return v.SetSuppressPopup(value)
}

func (impl *ToastNotification) GetSuppressPopup() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification2))
	defer itf.Release()
	v := (*iToastNotification2)(unsafe.Pointer(itf))
	return v.GetSuppressPopup()
}

func (impl *ToastNotification) GetNotificationMirroring() (NotificationMirroring, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification3))
	defer itf.Release()
	v := (*iToastNotification3)(unsafe.Pointer(itf))
	return v.GetNotificationMirroring()
}

func (impl *ToastNotification) SetNotificationMirroring(value NotificationMirroring) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification3))
	defer itf.Release()
	v := (*iToastNotification3)(unsafe.Pointer(itf))
	return v.SetNotificationMirroring(value)
}

func (impl *ToastNotification) GetRemoteId() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification3))
	defer itf.Release()
	v := (*iToastNotification3)(unsafe.Pointer(itf))
	return v.GetRemoteId()
}

func (impl *ToastNotification) SetRemoteId(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification3))
	defer itf.Release()
	v := (*iToastNotification3)(unsafe.Pointer(itf))
	return v.SetRemoteId(value)
}

func (impl *ToastNotification) GetData() (*NotificationData, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification4))
	defer itf.Release()
	v := (*iToastNotification4)(unsafe.Pointer(itf))
	return v.GetData()
}

func (impl *ToastNotification) SetData(value *NotificationData) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification4))
	defer itf.Release()
	v := (*iToastNotification4)(unsafe.Pointer(itf))
	return v.SetData(value)
}

func (impl *ToastNotification) GetPriority() (ToastNotificationPriority, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification4))
	defer itf.Release()
	v := (*iToastNotification4)(unsafe.Pointer(itf))
	return v.GetPriority()
}

func (impl *ToastNotification) SetPriority(value ToastNotificationPriority) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification4))
	defer itf.Release()
	v := (*iToastNotification4)(unsafe.Pointer(itf))
	return v.SetPriority(value)
}

func (impl *ToastNotification) GetExpiresOnReboot() (bool, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification6))
	defer itf.Release()
	v := (*iToastNotification6)(unsafe.Pointer(itf))
	return v.GetExpiresOnReboot()
}

func (impl *ToastNotification) SetExpiresOnReboot(value bool) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiToastNotification6))
	defer itf.Release()
	v := (*iToastNotification6)(unsafe.Pointer(itf))
	return v.SetExpiresOnReboot(value)
}

const GUIDiToastNotification string = "997e2675-059e-4e60-8b06-1760917c8b80"
const SignatureiToastNotification string = "{997e2675-059e-4e60-8b06-1760917c8b80}"

type iToastNotification struct {
	ole.IInspectable
}

type iToastNotificationVtbl struct {
	ole.IInspectableVtbl

	GetContent        uintptr
	SetExpirationTime uintptr
	GetExpirationTime uintptr
	AddDismissed      uintptr
	RemoveDismissed   uintptr
	AddActivated      uintptr
	RemoveActivated   uintptr
	AddFailed         uintptr
	RemoveFailed      uintptr
}

func (v *iToastNotification) VTable() *iToastNotificationVtbl {
	return (*iToastNotificationVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iToastNotification) GetContent() (*dom.XmlDocument, error) {
	var out *dom.XmlDocument
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetContent,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out dom.XmlDocument
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iToastNotification) SetExpirationTime(value *foundation.IReference) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetExpirationTime,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in foundation.IReference
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iToastNotification) GetExpirationTime() (*foundation.IReference, error) {
	var out *foundation.IReference
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetExpirationTime,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IReference
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iToastNotification) AddDismissed(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddDismissed,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iToastNotification) RemoveDismissed(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveDismissed,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iToastNotification) AddActivated(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddActivated,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iToastNotification) RemoveActivated(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveActivated,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iToastNotification) AddFailed(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddFailed,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *iToastNotification) RemoveFailed(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveFailed,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiToastNotification2 string = "9dfb9fd1-143a-490e-90bf-b9fba7132de7"
const SignatureiToastNotification2 string = "{9dfb9fd1-143a-490e-90bf-b9fba7132de7}"

type iToastNotification2 struct {
	ole.IInspectable
}

type iToastNotification2Vtbl struct {
	ole.IInspectableVtbl

	SetTag           uintptr
	GetTag           uintptr
	SetGroup         uintptr
	GetGroup         uintptr
	SetSuppressPopup uintptr
	GetSuppressPopup uintptr
}

func (v *iToastNotification2) VTable() *iToastNotification2Vtbl {
	return (*iToastNotification2Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iToastNotification2) SetTag(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetTag,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iToastNotification2) GetTag() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetTag,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iToastNotification2) SetGroup(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetGroup,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iToastNotification2) GetGroup() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetGroup,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iToastNotification2) SetSuppressPopup(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetSuppressPopup,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iToastNotification2) GetSuppressPopup() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSuppressPopup,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiToastNotification3 string = "31e8aed8-8141-4f99-bc0a-c4ed21297d77"
const SignatureiToastNotification3 string = "{31e8aed8-8141-4f99-bc0a-c4ed21297d77}"

type iToastNotification3 struct {
	ole.IInspectable
}

type iToastNotification3Vtbl struct {
	ole.IInspectableVtbl

	GetNotificationMirroring uintptr
	SetNotificationMirroring uintptr
	GetRemoteId              uintptr
	SetRemoteId              uintptr
}

func (v *iToastNotification3) VTable() *iToastNotification3Vtbl {
	return (*iToastNotification3Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iToastNotification3) GetNotificationMirroring() (NotificationMirroring, error) {
	var out NotificationMirroring
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetNotificationMirroring,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out NotificationMirroring
	)

	if hr != 0 {
		return NotificationMirroringAllowed, ole.NewError(hr)
	}

	return out, nil
}

func (v *iToastNotification3) SetNotificationMirroring(value NotificationMirroring) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetNotificationMirroring,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in NotificationMirroring
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iToastNotification3) GetRemoteId() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetRemoteId,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iToastNotification3) SetRemoteId(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetRemoteId,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiToastNotification4 string = "15154935-28ea-4727-88e9-c58680e2d118"
const SignatureiToastNotification4 string = "{15154935-28ea-4727-88e9-c58680e2d118}"

type iToastNotification4 struct {
	ole.IInspectable
}

type iToastNotification4Vtbl struct {
	ole.IInspectableVtbl

	GetData     uintptr
	SetData     uintptr
	GetPriority uintptr
	SetPriority uintptr
}

func (v *iToastNotification4) VTable() *iToastNotification4Vtbl {
	return (*iToastNotification4Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iToastNotification4) GetData() (*NotificationData, error) {
	var out *NotificationData
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetData,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out NotificationData
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iToastNotification4) SetData(value *NotificationData) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetData,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in NotificationData
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iToastNotification4) GetPriority() (ToastNotificationPriority, error) {
	var out ToastNotificationPriority
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPriority,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out ToastNotificationPriority
	)

	if hr != 0 {
		return ToastNotificationPriorityDefault, ole.NewError(hr)
	}

	return out, nil
}

func (v *iToastNotification4) SetPriority(value ToastNotificationPriority) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetPriority,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in ToastNotificationPriority
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiToastNotification6 string = "43ebfe53-89ae-5c1e-a279-3aecfe9b6f54"
const SignatureiToastNotification6 string = "{43ebfe53-89ae-5c1e-a279-3aecfe9b6f54}"

type iToastNotification6 struct {
	ole.IInspectable
}

type iToastNotification6Vtbl struct {
	ole.IInspectableVtbl

	GetExpiresOnReboot uintptr
	SetExpiresOnReboot uintptr
}

func (v *iToastNotification6) VTable() *iToastNotification6Vtbl {
	return (*iToastNotification6Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iToastNotification6) GetExpiresOnReboot() (bool, error) {
	var out bool
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetExpiresOnReboot,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out bool
	)

	if hr != 0 {
		return false, ole.NewError(hr)
	}

	return out, nil
}

func (v *iToastNotification6) SetExpiresOnReboot(value bool) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetExpiresOnReboot,
		uintptr(unsafe.Pointer(v)),                // this
		uintptr(*(*byte)(unsafe.Pointer(&value))), // in bool
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiToastNotificationFactory string = "04124b20-82c6-4229-b109-fd9ed4662b53"
const SignatureiToastNotificationFactory string = "{04124b20-82c6-4229-b109-fd9ed4662b53}"

type iToastNotificationFactory struct {
	ole.IInspectable
}

type iToastNotificationFactoryVtbl struct {
	ole.IInspectableVtbl

	ToastNotificationCreateToastNotification uintptr
}

func (v *iToastNotificationFactory) VTable() *iToastNotificationFactoryVtbl {
	return (*iToastNotificationFactoryVtbl)(unsafe.Pointer(v.RawVTable))
}

func ToastNotificationCreateToastNotification(content *dom.XmlDocument) (*ToastNotification, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.UI.Notifications.ToastNotification", ole.NewGUID(GUIDiToastNotificationFactory))
	if err != nil {
		return nil, err
	}
	v := (*iToastNotificationFactory)(unsafe.Pointer(inspectable))

	var out *ToastNotification
	hr, _, _ := syscall.SyscallN(
		v.VTable().ToastNotificationCreateToastNotification,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(content)), // in dom.XmlDocument
		uintptr(unsafe.Pointer(&out)),    // out ToastNotification
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
