// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package notifications

type ToastNotificationPriority int32

const SignatureToastNotificationPriority string = "enum(Windows.UI.Notifications.ToastNotificationPriority;i4)"

const (
	ToastNotificationPriorityDefault ToastNotificationPriority = 0
	ToastNotificationPriorityHigh    ToastNotificationPriority = 1
)
