// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/storage"
)

const GUIDiCachedFileUpdaterStatics string = "9fc90920-7bcf-4888-a81e-102d7034d7ce"
const SignatureiCachedFileUpdaterStatics string = "{9fc90920-7bcf-4888-a81e-102d7034d7ce}"

type iCachedFileUpdaterStatics struct {
	ole.IInspectable
}

type iCachedFileUpdaterStaticsVtbl struct {
	ole.IInspectableVtbl

	CachedFileUpdaterSetUpdateInformation uintptr
}

func (v *iCachedFileUpdaterStatics) VTable() *iCachedFileUpdaterStaticsVtbl {
	return (*iCachedFileUpdaterStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func CachedFileUpdaterSetUpdateInformation(file *storage.IStorageFile, contentId string, readMode ReadActivationMode, writeMode WriteActivationMode, options CachedFileOptions) error {
	inspectable, err := ole.RoGetActivationFactory("Windows.Storage.Provider.CachedFileUpdater", ole.NewGUID(GUIDiCachedFileUpdaterStatics))
	if err != nil {
		return err
	}
	v := (*iCachedFileUpdaterStatics)(unsafe.Pointer(inspectable))

	contentIdHStr, err := ole.NewHString(contentId)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().CachedFileUpdaterSetUpdateInformation,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(file)), // in storage.IStorageFile
		uintptr(contentIdHStr),        // in string
		uintptr(readMode),             // in ReadActivationMode
		uintptr(writeMode),            // in WriteActivationMode
		uintptr(options),              // in CachedFileOptions
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
