// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type CachedFileOptions uint32

const SignatureCachedFileOptions string = "enum(Windows.Storage.Provider.CachedFileOptions;u4)"

const (
	CachedFileOptionsNone                     CachedFileOptions = 0
	CachedFileOptionsRequireUpdateOnAccess    CachedFileOptions = 1
	CachedFileOptionsUseCachedFileWhenOffline CachedFileOptions = 2
	CachedFileOptionsDenyAccessWhenOffline    CachedFileOptions = 4
)
