// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const GUIDIStorageProviderUICommand string = "0c3e0760-d846-568f-9484-105cc57b502b"
const SignatureIStorageProviderUICommand string = "{0c3e0760-d846-568f-9484-105cc57b502b}"

type IStorageProviderUICommand struct {
	ole.IInspectable
}

type IStorageProviderUICommandVtbl struct {
	ole.IInspectableVtbl

	GetLabel       uintptr
	GetDescription uintptr
	GetIcon        uintptr
	GetState       uintptr
	Invoke         uintptr
}

func (v *IStorageProviderUICommand) VTable() *IStorageProviderUICommandVtbl {
	return (*IStorageProviderUICommandVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *IStorageProviderUICommand) GetLabel() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetLabel,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *IStorageProviderUICommand) GetDescription() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDescription,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *IStorageProviderUICommand) GetIcon() (*foundation.Uri, error) {
	var out *foundation.Uri
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetIcon,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.Uri
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *IStorageProviderUICommand) GetState() (StorageProviderUICommandState, error) {
	var out StorageProviderUICommandState
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetState,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderUICommandState
	)

	if hr != 0 {
		return StorageProviderUICommandStateEnabled, ole.NewError(hr)
	}

	return out, nil
}

func (v *IStorageProviderUICommand) Invoke() error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().Invoke,
		uintptr(unsafe.Pointer(v)), // this
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
