// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const GUIDIStorageProviderStatusUISource string = "a306c249-3d66-5e70-9007-e43df96051ff"
const SignatureIStorageProviderStatusUISource string = "{a306c249-3d66-5e70-9007-e43df96051ff}"

type IStorageProviderStatusUISource struct {
	ole.IInspectable
}

type IStorageProviderStatusUISourceVtbl struct {
	ole.IInspectableVtbl

	GetStatusUI           uintptr
	AddStatusUIChanged    uintptr
	RemoveStatusUIChanged uintptr
}

func (v *IStorageProviderStatusUISource) VTable() *IStorageProviderStatusUISourceVtbl {
	return (*IStorageProviderStatusUISourceVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *IStorageProviderStatusUISource) GetStatusUI() (*StorageProviderStatusUI, error) {
	var out *StorageProviderStatusUI
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetStatusUI,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderStatusUI
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *IStorageProviderStatusUISource) AddStatusUIChanged(handler *foundation.TypedEventHandler) (foundation.EventRegistrationToken, error) {
	var out foundation.EventRegistrationToken
	hr, _, _ := syscall.SyscallN(
		v.VTable().AddStatusUIChanged,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(handler)), // in foundation.TypedEventHandler
		uintptr(unsafe.Pointer(&out)),    // out foundation.EventRegistrationToken
	)

	if hr != 0 {
		return foundation.EventRegistrationToken{}, ole.NewError(hr)
	}

	return out, nil
}

func (v *IStorageProviderStatusUISource) RemoveStatusUIChanged(token foundation.EventRegistrationToken) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().RemoveStatusUIChanged,
		uintptr(unsafe.Pointer(v)),      // this
		uintptr(unsafe.Pointer(&token)), // in foundation.EventRegistrationToken
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
