// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type ReadActivationMode int32

const SignatureReadActivationMode string = "enum(Windows.Storage.Provider.ReadActivationMode;i4)"

const (
	ReadActivationModeNotNeeded    ReadActivationMode = 0
	ReadActivationModeBeforeAccess ReadActivationMode = 1
)
