// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const SignatureStorageProviderQuotaUI string = "rc(Windows.Storage.Provider.StorageProviderQuotaUI;{ba6295c3-312e-544f-9fd5-1f81b21f3649})"

type StorageProviderQuotaUI struct {
	ole.IUnknown
}

func NewStorageProviderQuotaUI() (*StorageProviderQuotaUI, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Storage.Provider.StorageProviderQuotaUI")
	if err != nil {
		return nil, err
	}
	return (*StorageProviderQuotaUI)(unsafe.Pointer(inspectable)), nil
}

func (impl *StorageProviderQuotaUI) GetQuotaTotalInBytes() (uint64, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderQuotaUI))
	defer itf.Release()
	v := (*iStorageProviderQuotaUI)(unsafe.Pointer(itf))
	return v.GetQuotaTotalInBytes()
}

func (impl *StorageProviderQuotaUI) SetQuotaTotalInBytes(value uint64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderQuotaUI))
	defer itf.Release()
	v := (*iStorageProviderQuotaUI)(unsafe.Pointer(itf))
	return v.SetQuotaTotalInBytes(value)
}

func (impl *StorageProviderQuotaUI) GetQuotaUsedInBytes() (uint64, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderQuotaUI))
	defer itf.Release()
	v := (*iStorageProviderQuotaUI)(unsafe.Pointer(itf))
	return v.GetQuotaUsedInBytes()
}

func (impl *StorageProviderQuotaUI) SetQuotaUsedInBytes(value uint64) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderQuotaUI))
	defer itf.Release()
	v := (*iStorageProviderQuotaUI)(unsafe.Pointer(itf))
	return v.SetQuotaUsedInBytes(value)
}

func (impl *StorageProviderQuotaUI) GetQuotaUsedLabel() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderQuotaUI))
	defer itf.Release()
	v := (*iStorageProviderQuotaUI)(unsafe.Pointer(itf))
	return v.GetQuotaUsedLabel()
}

func (impl *StorageProviderQuotaUI) SetQuotaUsedLabel(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderQuotaUI))
	defer itf.Release()
	v := (*iStorageProviderQuotaUI)(unsafe.Pointer(itf))
	return v.SetQuotaUsedLabel(value)
}

func (impl *StorageProviderQuotaUI) GetQuotaUsedColor() (*foundation.IReference, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderQuotaUI))
	defer itf.Release()
	v := (*iStorageProviderQuotaUI)(unsafe.Pointer(itf))
	return v.GetQuotaUsedColor()
}

func (impl *StorageProviderQuotaUI) SetQuotaUsedColor(value *foundation.IReference) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderQuotaUI))
	defer itf.Release()
	v := (*iStorageProviderQuotaUI)(unsafe.Pointer(itf))
	return v.SetQuotaUsedColor(value)
}

const GUIDiStorageProviderQuotaUI string = "ba6295c3-312e-544f-9fd5-1f81b21f3649"
const SignatureiStorageProviderQuotaUI string = "{ba6295c3-312e-544f-9fd5-1f81b21f3649}"

type iStorageProviderQuotaUI struct {
	ole.IInspectable
}

type iStorageProviderQuotaUIVtbl struct {
	ole.IInspectableVtbl

	GetQuotaTotalInBytes uintptr
	SetQuotaTotalInBytes uintptr
	GetQuotaUsedInBytes  uintptr
	SetQuotaUsedInBytes  uintptr
	GetQuotaUsedLabel    uintptr
	SetQuotaUsedLabel    uintptr
	GetQuotaUsedColor    uintptr
	SetQuotaUsedColor    uintptr
}

func (v *iStorageProviderQuotaUI) VTable() *iStorageProviderQuotaUIVtbl {
	return (*iStorageProviderQuotaUIVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStorageProviderQuotaUI) GetQuotaTotalInBytes() (uint64, error) {
	var out uint64
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetQuotaTotalInBytes,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint64
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderQuotaUI) SetQuotaTotalInBytes(value uint64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetQuotaTotalInBytes,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in uint64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderQuotaUI) GetQuotaUsedInBytes() (uint64, error) {
	var out uint64
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetQuotaUsedInBytes,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint64
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderQuotaUI) SetQuotaUsedInBytes(value uint64) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetQuotaUsedInBytes,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in uint64
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderQuotaUI) GetQuotaUsedLabel() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetQuotaUsedLabel,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iStorageProviderQuotaUI) SetQuotaUsedLabel(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetQuotaUsedLabel,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderQuotaUI) GetQuotaUsedColor() (*foundation.IReference, error) {
	var out *foundation.IReference
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetQuotaUsedColor,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IReference
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderQuotaUI) SetQuotaUsedColor(value *foundation.IReference) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetQuotaUsedColor,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in foundation.IReference
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
