// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type StorageProviderUICommandState int32

const SignatureStorageProviderUICommandState string = "enum(Windows.Storage.Provider.StorageProviderUICommandState;i4)"

const (
	StorageProviderUICommandStateEnabled  StorageProviderUICommandState = 0
	StorageProviderUICommandStateDisabled StorageProviderUICommandState = 1
	StorageProviderUICommandStateHidden   StorageProviderUICommandState = 2
)
