// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type StorageProviderState int32

const SignatureStorageProviderState string = "enum(Windows.Storage.Provider.StorageProviderState;i4)"

const (
	StorageProviderStateInSync  StorageProviderState = 0
	StorageProviderStateSyncing StorageProviderState = 1
	StorageProviderStatePaused  StorageProviderState = 2
	StorageProviderStateError   StorageProviderState = 3
	StorageProviderStateWarning StorageProviderState = 4
	StorageProviderStateOffline StorageProviderState = 5
)
