// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureStorageProviderMoreInfoUI string = "rc(Windows.Storage.Provider.StorageProviderMoreInfoUI;{ef38e591-a7cb-5e7d-9b5e-22749842697c})"

type StorageProviderMoreInfoUI struct {
	ole.IUnknown
}

func NewStorageProviderMoreInfoUI() (*StorageProviderMoreInfoUI, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Storage.Provider.StorageProviderMoreInfoUI")
	if err != nil {
		return nil, err
	}
	return (*StorageProviderMoreInfoUI)(unsafe.Pointer(inspectable)), nil
}

func (impl *StorageProviderMoreInfoUI) GetMessage() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderMoreInfoUI))
	defer itf.Release()
	v := (*iStorageProviderMoreInfoUI)(unsafe.Pointer(itf))
	return v.GetMessage()
}

func (impl *StorageProviderMoreInfoUI) SetMessage(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderMoreInfoUI))
	defer itf.Release()
	v := (*iStorageProviderMoreInfoUI)(unsafe.Pointer(itf))
	return v.SetMessage(value)
}

func (impl *StorageProviderMoreInfoUI) GetCommand() (*IStorageProviderUICommand, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderMoreInfoUI))
	defer itf.Release()
	v := (*iStorageProviderMoreInfoUI)(unsafe.Pointer(itf))
	return v.GetCommand()
}

func (impl *StorageProviderMoreInfoUI) SetCommand(value *IStorageProviderUICommand) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderMoreInfoUI))
	defer itf.Release()
	v := (*iStorageProviderMoreInfoUI)(unsafe.Pointer(itf))
	return v.SetCommand(value)
}

const GUIDiStorageProviderMoreInfoUI string = "ef38e591-a7cb-5e7d-9b5e-22749842697c"
const SignatureiStorageProviderMoreInfoUI string = "{ef38e591-a7cb-5e7d-9b5e-22749842697c}"

type iStorageProviderMoreInfoUI struct {
	ole.IInspectable
}

type iStorageProviderMoreInfoUIVtbl struct {
	ole.IInspectableVtbl

	GetMessage uintptr
	SetMessage uintptr
	GetCommand uintptr
	SetCommand uintptr
}

func (v *iStorageProviderMoreInfoUI) VTable() *iStorageProviderMoreInfoUIVtbl {
	return (*iStorageProviderMoreInfoUIVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStorageProviderMoreInfoUI) GetMessage() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetMessage,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iStorageProviderMoreInfoUI) SetMessage(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetMessage,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderMoreInfoUI) GetCommand() (*IStorageProviderUICommand, error) {
	var out *IStorageProviderUICommand
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetCommand,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out IStorageProviderUICommand
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderMoreInfoUI) SetCommand(value *IStorageProviderUICommand) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetCommand,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in IStorageProviderUICommand
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
