// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/foundation/collections"
)

const SignatureStorageProviderStatusUI string = "rc(Windows.Storage.Provider.StorageProviderStatusUI;{d6b6a758-198d-5b80-977f-5ff73da33118})"

type StorageProviderStatusUI struct {
	ole.IUnknown
}

func NewStorageProviderStatusUI() (*StorageProviderStatusUI, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Storage.Provider.StorageProviderStatusUI")
	if err != nil {
		return nil, err
	}
	return (*StorageProviderStatusUI)(unsafe.Pointer(inspectable)), nil
}

func (impl *StorageProviderStatusUI) GetProviderState() (StorageProviderState, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.GetProviderState()
}

func (impl *StorageProviderStatusUI) SetProviderState(value StorageProviderState) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.SetProviderState(value)
}

func (impl *StorageProviderStatusUI) GetProviderStateLabel() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.GetProviderStateLabel()
}

func (impl *StorageProviderStatusUI) SetProviderStateLabel(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.SetProviderStateLabel(value)
}

func (impl *StorageProviderStatusUI) GetProviderStateIcon() (*foundation.Uri, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.GetProviderStateIcon()
}

func (impl *StorageProviderStatusUI) SetProviderStateIcon(value *foundation.Uri) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.SetProviderStateIcon(value)
}

func (impl *StorageProviderStatusUI) GetSyncStatusCommand() (*IStorageProviderUICommand, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.GetSyncStatusCommand()
}

func (impl *StorageProviderStatusUI) SetSyncStatusCommand(value *IStorageProviderUICommand) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.SetSyncStatusCommand(value)
}

func (impl *StorageProviderStatusUI) GetQuotaUI() (*StorageProviderQuotaUI, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.GetQuotaUI()
}

func (impl *StorageProviderStatusUI) SetQuotaUI(value *StorageProviderQuotaUI) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.SetQuotaUI(value)
}

func (impl *StorageProviderStatusUI) GetMoreInfoUI() (*StorageProviderMoreInfoUI, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.GetMoreInfoUI()
}

func (impl *StorageProviderStatusUI) SetMoreInfoUI(value *StorageProviderMoreInfoUI) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.SetMoreInfoUI(value)
}

func (impl *StorageProviderStatusUI) GetProviderPrimaryCommand() (*IStorageProviderUICommand, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.GetProviderPrimaryCommand()
}

func (impl *StorageProviderStatusUI) SetProviderPrimaryCommand(value *IStorageProviderUICommand) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.SetProviderPrimaryCommand(value)
}

func (impl *StorageProviderStatusUI) GetProviderSecondaryCommands() (*collections.IVector, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.GetProviderSecondaryCommands()
}

func (impl *StorageProviderStatusUI) SetProviderSecondaryCommands(value *collections.IVector) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderStatusUI))
	defer itf.Release()
	v := (*iStorageProviderStatusUI)(unsafe.Pointer(itf))
	return v.SetProviderSecondaryCommands(value)
}

const GUIDiStorageProviderStatusUI string = "d6b6a758-198d-5b80-977f-5ff73da33118"
const SignatureiStorageProviderStatusUI string = "{d6b6a758-198d-5b80-977f-5ff73da33118}"

type iStorageProviderStatusUI struct {
	ole.IInspectable
}

type iStorageProviderStatusUIVtbl struct {
	ole.IInspectableVtbl

	GetProviderState             uintptr
	SetProviderState             uintptr
	GetProviderStateLabel        uintptr
	SetProviderStateLabel        uintptr
	GetProviderStateIcon         uintptr
	SetProviderStateIcon         uintptr
	GetSyncStatusCommand         uintptr
	SetSyncStatusCommand         uintptr
	GetQuotaUI                   uintptr
	SetQuotaUI                   uintptr
	GetMoreInfoUI                uintptr
	SetMoreInfoUI                uintptr
	GetProviderPrimaryCommand    uintptr
	SetProviderPrimaryCommand    uintptr
	GetProviderSecondaryCommands uintptr
	SetProviderSecondaryCommands uintptr
}

func (v *iStorageProviderStatusUI) VTable() *iStorageProviderStatusUIVtbl {
	return (*iStorageProviderStatusUIVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStorageProviderStatusUI) GetProviderState() (StorageProviderState, error) {
	var out StorageProviderState
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetProviderState,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderState
	)

	if hr != 0 {
		return StorageProviderStateInSync, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderStatusUI) SetProviderState(value StorageProviderState) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetProviderState,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in StorageProviderState
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderStatusUI) GetProviderStateLabel() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetProviderStateLabel,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iStorageProviderStatusUI) SetProviderStateLabel(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetProviderStateLabel,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderStatusUI) GetProviderStateIcon() (*foundation.Uri, error) {
	var out *foundation.Uri
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetProviderStateIcon,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.Uri
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderStatusUI) SetProviderStateIcon(value *foundation.Uri) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetProviderStateIcon,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in foundation.Uri
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderStatusUI) GetSyncStatusCommand() (*IStorageProviderUICommand, error) {
	var out *IStorageProviderUICommand
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetSyncStatusCommand,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out IStorageProviderUICommand
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderStatusUI) SetSyncStatusCommand(value *IStorageProviderUICommand) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetSyncStatusCommand,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in IStorageProviderUICommand
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderStatusUI) GetQuotaUI() (*StorageProviderQuotaUI, error) {
	var out *StorageProviderQuotaUI
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetQuotaUI,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderQuotaUI
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderStatusUI) SetQuotaUI(value *StorageProviderQuotaUI) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetQuotaUI,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in StorageProviderQuotaUI
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderStatusUI) GetMoreInfoUI() (*StorageProviderMoreInfoUI, error) {
	var out *StorageProviderMoreInfoUI
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetMoreInfoUI,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out StorageProviderMoreInfoUI
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderStatusUI) SetMoreInfoUI(value *StorageProviderMoreInfoUI) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetMoreInfoUI,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in StorageProviderMoreInfoUI
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderStatusUI) GetProviderPrimaryCommand() (*IStorageProviderUICommand, error) {
	var out *IStorageProviderUICommand
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetProviderPrimaryCommand,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out IStorageProviderUICommand
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderStatusUI) SetProviderPrimaryCommand(value *IStorageProviderUICommand) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetProviderPrimaryCommand,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in IStorageProviderUICommand
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderStatusUI) GetProviderSecondaryCommands() (*collections.IVector, error) {
	var out *collections.IVector
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetProviderSecondaryCommands,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVector
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderStatusUI) SetProviderSecondaryCommands(value *collections.IVector) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetProviderSecondaryCommands,
		uintptr(unsafe.Pointer(v)),     // this
		uintptr(unsafe.Pointer(value)), // in collections.IVector
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
