// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureStorageProviderItemPropertyDefinition string = "rc(Windows.Storage.Provider.StorageProviderItemPropertyDefinition;{c5b383bb-ff1f-4298-831e-ff1c08089690})"

type StorageProviderItemPropertyDefinition struct {
	ole.IUnknown
}

func NewStorageProviderItemPropertyDefinition() (*StorageProviderItemPropertyDefinition, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Storage.Provider.StorageProviderItemPropertyDefinition")
	if err != nil {
		return nil, err
	}
	return (*StorageProviderItemPropertyDefinition)(unsafe.Pointer(inspectable)), nil
}

func (impl *StorageProviderItemPropertyDefinition) GetId() (int32, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderItemPropertyDefinition))
	defer itf.Release()
	v := (*iStorageProviderItemPropertyDefinition)(unsafe.Pointer(itf))
	return v.GetId()
}

func (impl *StorageProviderItemPropertyDefinition) SetId(value int32) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderItemPropertyDefinition))
	defer itf.Release()
	v := (*iStorageProviderItemPropertyDefinition)(unsafe.Pointer(itf))
	return v.SetId(value)
}

func (impl *StorageProviderItemPropertyDefinition) GetDisplayNameResource() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderItemPropertyDefinition))
	defer itf.Release()
	v := (*iStorageProviderItemPropertyDefinition)(unsafe.Pointer(itf))
	return v.GetDisplayNameResource()
}

func (impl *StorageProviderItemPropertyDefinition) SetDisplayNameResource(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiStorageProviderItemPropertyDefinition))
	defer itf.Release()
	v := (*iStorageProviderItemPropertyDefinition)(unsafe.Pointer(itf))
	return v.SetDisplayNameResource(value)
}

const GUIDiStorageProviderItemPropertyDefinition string = "c5b383bb-ff1f-4298-831e-ff1c08089690"
const SignatureiStorageProviderItemPropertyDefinition string = "{c5b383bb-ff1f-4298-831e-ff1c08089690}"

type iStorageProviderItemPropertyDefinition struct {
	ole.IInspectable
}

type iStorageProviderItemPropertyDefinitionVtbl struct {
	ole.IInspectableVtbl

	GetId                  uintptr
	SetId                  uintptr
	GetDisplayNameResource uintptr
	SetDisplayNameResource uintptr
}

func (v *iStorageProviderItemPropertyDefinition) VTable() *iStorageProviderItemPropertyDefinitionVtbl {
	return (*iStorageProviderItemPropertyDefinitionVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iStorageProviderItemPropertyDefinition) GetId() (int32, error) {
	var out int32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetId,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out int32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iStorageProviderItemPropertyDefinition) SetId(value int32) error {
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetId,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(value),             // in int32
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

func (v *iStorageProviderItemPropertyDefinition) GetDisplayNameResource() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetDisplayNameResource,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iStorageProviderItemPropertyDefinition) SetDisplayNameResource(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetDisplayNameResource,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}
