// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package provider

type WriteActivationMode int32

const SignatureWriteActivationMode string = "enum(Windows.Storage.Provider.WriteActivationMode;i4)"

const (
	WriteActivationModeReadOnly   WriteActivationMode = 0
	WriteActivationModeNotNeeded  WriteActivationMode = 1
	WriteActivationModeAfterWrite WriteActivationMode = 2
)
